# Default values for voting-app-result.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dockersamples/examplevotingapp_result
  tag: before
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5001
  nodePort: 31002

ext:
  db: voting-app-db