# Default values for voting-app-vote.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dockersamples/examplevotingapp_vote
  tag: before
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000
  nodePort: 31001

ext:
  redis: voting-app-redis