apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app.kubernetes.io/name: {{ include "voting-app-result.name" . }}
    helm.sh/chart: {{ include "voting-app-result.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ExternalName
  externalName: db.{{ ext.db }}.svc.cluster.local