apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: {{ include "voting-app-vote.name" . }}
    helm.sh/chart: {{ include "voting-app-vote.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ExternalName
  externalName: redis.{{ ext.redis }}.svc.cluster.local