apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app.kubernetes.io/name: {{ include "voting-app-vote.name" . }}
    helm.sh/chart: {{ include "voting-app-vote.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80      
  selector:
    app.kubernetes.io/name: {{ include "voting-app-vote.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
