apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app.kubernetes.io/name: {{ include "voting-app-vote.name" . }}
    helm.sh/chart: {{ include "voting-app-vote.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      {{ if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    app.kubernetes.io/name: {{ include "voting-app-vote.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
